/****************************************************************************** 
 * verify_microgrid.sql
 * SQL script for verifying data loaded in tables in sagrid database for the
 * microgrid project
 *****************************************************************************/

\! echo "USE sagrid"
USE sagrid

SET @start_date_time = '2017-02-03 14:00:00', @end_date_time = '2017-05-27 14:30:00';

\! echo "SELECT earliest date/time by household INTO OUTFILE /home/silvio/mysql/out/hh_start_date.csv"
SELECT hh_id, min(date_time_utc) start_utc
FROM hh_energy
GROUP BY hh_id
ORDER BY start_utc, hh_id
INTO OUTFILE '/home/silvio/mysql/out/hh_start_date.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT latest date/time by household INTO OUTFILE /home/silvio/mysql/out/hh_end_date.csv"
SELECT hh_id, max(date_time_utc) end_utc
FROM hh_energy
GROUP BY hh_id
ORDER BY end_utc, hh_id
INTO OUTFILE '/home/silvio/mysql/out/hh_end_date.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT count time intervals by household INTO OUTFILE /home/silvio/mysql/out/hh_time_intervals.csv"
SELECT hh_id, count(*) time_intervals
FROM hh_energy
GROUP BY hh_id
ORDER BY time_intervals, hh_id
INTO OUTFILE '/home/silvio/mysql/out/hh_interval_count.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT * FROM hh_energy WHERE hh_id = 99 INTO OUTFILE /home/silvio/mysql/out/hh_id_99.csv"
SELECT dt.date_time_utc, dt.date_time_act, he.hh_id, he.hh_solar_kwh, he.hh_bess_chrg_kwh, he.hh_load_kwh, he.hh_grid_kwh
FROM date_time dt LEFT JOIN hh_energy he
ON (dt.date_time_utc = he.date_time_utc AND he.hh_id = 99)
WHERE (dt.date_time_act > @start_date_time AND dt.date_time_act < @end_date_time)
ORDER BY dt.date_time_utc
INTO OUTFILE '/home/silvio/mysql/out/hh_id_99.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT * FROM mg_hh, date_time WHERE date_time_utc NOT IN hh_energy INTO OUTFILE /home/silvio/mysql/out/hhid_datetime_notexist.csv"
SELECT mh.hh_id, dt.date_time_utc, dt.date_time_act, he.hh_id
FROM mg_hh mh JOIN date_time dt LEFT JOIN hh_energy he
ON (mh.hh_id = he.hh_id AND dt.date_time_utc = he.date_time_utc)
WHERE (dt.date_time_utc >= @start_date_time AND dt.date_time_utc < @start_date_time)
AND he.hh_id IS NULL
ORDER BY mh.hh_id, dt.date_time_utc
INTO OUTFILE '/home/silvio/mysql/out/hhid_datetime_notexist.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT COUNT(*) FROM hh_energy WHERE hh_intrpl = TRUE INTO OUTFILE /home/silvio/mysql/out/hh_intrpl_count.csv"
SELECT hh_id, COUNT(*) intrpl_count
FROM hh_energy
WHERE hh_intrpl = TRUE
GROUP BY hh_id
ORDER BY hh_id
INTO OUTFILE '/home/silvio/mysql/out/hh_intrpl_count.csv'
COLUMNS TERMINATED BY ','
;

\! echo "SELECT * FROM hh_energy, date_time WHERE hh_intrpl = TRUE INTO OUTFILE /home/silvio/mysql/out/hh_intrpl_recs.csv"
SELECT he.hh_id, he.date_time_utc, dt.date_time_act he.hh_intrpl
FROM hh_energy he, date_time dt
WHERE he.date_time_utc = dt.date_time_utc
AND he.hh_intrpl = TRUE
ORDER BY he.hh_id, he.date_time_utc
INTO OUTFILE '/home/silvio/mysql/out/hh_intrpl_recs.csv'
COLUMNS TERMINATED BY ','
;

\! echo "Check maximum load (consumption) and solar power generated by a household by time interval"
SELECT TIME(dt.date_time_act), COUNT(*), MAX(hp.hh_load_kw), MAX(hp.hh_solar_kw)
FROM hh_power hp, date_time dt
WHERE hp.date_time_utc = dt.date_time_utc
GROUP BY TIME(dt.date_time_act)
ORDER BY TIME(dt.date_time_act)
INTO OUTFILE '/home/silvio/mysql/out/max_hh_power_time.csv'
COLUMNS TERMINATED BY ','
;

\! echo "Check maximum load (consumption) and solar energy generated by the microgrid by time interval"
SELECT TIME(dt.date_time_act), COUNT(*), MAX(mp.mg_load_kw), MAX(mp.mg_solar_kw)
FROM mg_power mp, date_time dt
WHERE mp.date_time_utc = dt.date_time_utc
GROUP BY TIME(dt.date_time_act)
ORDER BY TIME(dt.date_time_act)
INTO OUTFILE '/home/silvio/mysql/out/max_mg_power_time.csv'
COLUMNS TERMINATED BY ','
;


\! echo "Check maximum absolute values of columns in household data from Salisbury trial (mg_feed)"
SELECT hh_id, MAX(hh_bess_chrg_kwh), -MIN(hh_bess_dchrg_kwh), MAX(hh_load_kwh), MAX(hh_import_kwh), -MIN(hh_export_kwh), MAX(hh_net_kwh), MAX(hh_solar_kwh)
FROM mg_feed
GROUP BY hh_id
ORDER BY hh_id
INTO OUTFILE '/home/silvio/mysql/out/mg_feed_max_abs.csv'
COLUMNS TERMINATED BY ','
;
